name: Download Flutter Engine Artifact

on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Download engine artifact
        run: |
          mkdir engine
          cd engine

          URL="https://storage.googleapis.com/flutter_infra_release/flutter/6c0baaebf70e0148f485f27d5616b3d3382da7bf/android-arm-profile/windows-x64.zip"

          echo "Downloading $URL"
          curl -L --fail "$URL" -o windows-x64.zip

          ls -lh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-engine
          path: engine/windows-x64.zip

