name: Download Flutter Engine Artifact

on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Download android-arm-profile/windows-x64.zip
        run: |
          mkdir engine
          cd engine
          wget https://storage.googleapis.com/flutter_infra_release/flutter/6c0baaebf70e0148f485f27d5616b3d3382da7bf/android-arm-profile/windows-x64.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-x64
          path: engine/windows-x64.zip
